project:
  render: 
    - Courses/Applications/02_0_Numpy_Workout.qmd
    - Courses/01_Code-Assistant.qmd
    - Courses/02_Parallel-intro.qmd
    - Courses/03_Asynchronous.qmd
    - Courses/04_IPC-and-Locking.qmd
    - Courses/05_Distributed.qmd
    - Courses/06_Dask-Ray.qmd
    - Courses/07_Dask-delayed.qmd
    - Courses/08_SIMD.qmd
  pre-render: project-scripts/prepare-slides.py
  output-dir: docs-resources/Slides
  resources:
    - "Courses/tikz-figures/*.svg"  
    - "!/docs"
    - "!/docs-resources"


history: true
lang: en-EN
toc: true
toc-depth: 1
tbl-colwidths: [60, 50, 40, 30, 30]
code-line-numbers: false
format:
    revealjs: 
      output-ext: revealjs.html
      slide-number: h/v
      theme: [black, styles.scss]
      html-math-method: katex
      navigation-mode: vertical
      controls-tutorial: true
      preview-links: auto
      logo: images/paulva_logo.svg
      header-logo: images/logo-miashs.png
      footer: <span style="color:yellow;float:left;margin-left:7%;"><em>{{< meta title >}}</em></span><span style="color:grey;float:right;margin-right:12%;">Advanced Programming and Parallel Computing, Master 2 MIASHS</span>
      transition: convex
      fig-align: "center"
      center: true
      width: 1600
      height: 900
      margin: 0.15
      auto-stretch: true
      controls: false
      code-annotations: select
      chalkboard: true
revealjs-plugins:
  - attribution
  - animate
filters: 
    - animate
    - reveal-header
    - filters/make-transparent-img.lua
    - filters/slides-meta.lua
editor:
  render-on-save: true
slide-level: 2

  