project:
  render:
    - Courses/Applications/*.qmd
    - Courses/Solutions/01_0_Code-Assistant-prompt-engineering.qmd
    - Courses/Solutions/01_1_AI-Agent-sol.qmd
    # - Courses/Solutions/0_Numpy_Workout-sol.qmd
    # - Courses/Solutions/1_0_MultiProcessing_tutorial-sol.qmd
    # - Courses/Solutions/1_1_MultiProcessing-sol.qmd
    # - Courses/Solutions/2_Scaling-sol.qmd
    # - Courses/Solutions/3_0_Asynchronous-sol.qmd
    # - Courses/Solutions/3_1_Decorators_tutorial-sol.qmd
    # - Courses/Solutions/4_0_IPC_and_Locking-sol.qmd
    # - Courses/Solutions/4_1_IPC_and_Locking_cont-sol.qmd
    # - Courses/Solutions/4_2_Generators_tutorial-sol.qmd
    # - Courses/Solutions/5_0_Distributed_models-sol.qmd
    # - Courses/Solutions/5_1_Dask_delayed-sol.qmd
    # - Courses/Solutions/6_0_Numba_tutorial-sol.qmd
    # - Courses/Solutions/6_2_Simd_numba_autovec_tutorial-sol.qmd
    # - Courses/Solutions/7_0_GPU-sol.qmd
    # - Courses/Solutions/7_1_Cache-sol.qmd

  output-dir: docs-resources/Notebooks
  pre-render: project-scripts/prepare-notebooks.py
  post-render: project-scripts/convert.py
  resources:
    - "Courses/tikz-figures/*.svg"
    - "Courses/figs/*.png"
    - "materials/*"
    - "!/docs"
    - "!/docs-resources"

theme:
  dark: darkly
  light: flatly
  
format:
  ipynb:
    date: "2025-08-27"
    date-format: full
    toc: true
  html:
    number-depth: 3
    toc-depth: 4
    html-math-method: katex
    code-fold: show
    code-tools: true
    echo: true

execute: 
  eval: true
  output: true
  cache: true


filters:
  - filters/unclutter-slides.lua
  - filters/unclutter-tp.lua
  - filters/notebooks-meta.lua
