project:
  render:
    - Courses/Applications/*.qmd
    - Courses/Solutions/01_0_Code-Assistant-prompt-engineering-sol.qmd
    - Courses/Solutions/01_1_AI-Agent-sol.qmd
    - Courses/Solutions/02_0_Numpy_Workout.qmd
    - Courses/Solutions/02_1_Decorators_tutorial-sol.qmd
    - Courses/Solutions/02_2_Generators_tutorial-sol.qmd
    - Courses/Solutions/02_3_MultiProcessing_tutorial-sol.qmd
    - Courses/Solutions/02_4_Scaling.qmd
  output-dir: docs-resources/Notebooks
  pre-render: project-scripts/prepare-notebooks.py
  post-render: project-scripts/convert.py
  resources:
    - "Courses/tikz-figures/*.svg"
    - "Courses/figs/*.png"
    - "materials/alice.txt"
    - "!/docs"
    - "!/docs-resources"

theme:
  dark: darkly
  light: flatly
  
format:
  ipynb:
    date: "2025-08-27"
    date-format: full
    toc: true
  html:
    number-depth: 3
    toc-depth: 4
    html-math-method: katex
    code-fold: show
    code-tools: true
    echo: true

execute: 
  eval: true
  output: true
  cache: true


filters:
  - filters/unclutter-slides.lua
  - filters/unclutter-tp.lua
  - filters/notebooks-meta.lua
