grid-rows:3
vertical-gap: 0

style: {
    fill: transparent
}

classes : {
    invisible : {
        style : {
            fill: transparent
            stroke: transparent
        }
    }
}

1 : "" {
    class: invisible
    grid-columns: 2
    horizontal-gap: 0
    cont: "" {
        grid-rows: 2
        vertical-gap: 0
        class: invisible
        1000top: "1000" { 
            class: invisible
            label.near: bottom-center
         }
        1000 {
            label.near: outside-left-center
            width: 120
            height: 120
        }
    }
    1 processor: { class: invisible }
}

2.cont.500cont_*:  "" {
            grid-rows: 2
            vertical-gap: 0
            class: invisible
            1000top: "1000" { 
                class: invisible
                label.near: bottom-center
            }
            1000 {
                label.near: outside-left-center
                width: 120
                height: 120
            }
        }


2 : "" {
    class: invisible
    grid-columns: 2
    horizontal-gap: 0

    cont: "" {
        class: invisible
        grid-rows: 2
        grid-columns: 2
        horizontal-gap: 0
        vertical-gap: 0
        500cont_1
        500cont_2
        500cont_3
        500cont_4
    }
    4 processors: { class: invisible }
}

3.cont.250cont_*:  "" {
            grid-rows: 2
            vertical-gap: 0
            class: invisible
            1000top: "1000" { 
                class: invisible
                label.near: bottom-center
            }
            1000 {
                label.near: outside-left-center
                width: 120
                height: 120
            }
        }

3 : "" {
    class: invisible
    grid-columns: 2
    horizontal-gap: 0
    cont: "" {
        class: invisible
        grid-rows: 4
        grid-columns: 4
        horizontal-gap: 0
        vertical-gap: 0
        250cont_1
        250cont_2
        250cont_3
        250cont_4
        250cont_5
        250cont_6
        250cont_7
        250cont_8
        250cont_9
        250cont_10
        250cont_11
        250cont_12
        250cont_13
        250cont_14
        250cont_15
        250cont_16
    }
    16 processors: { class: invisible }
}

1.cont -> 2.cont -> 3.cont : "multiply" { 
    style {
        animated: true
        stroke-width: 10
        font-size: 32
    } 
}

*.* processor*.style.font-size: 32